const vocabularyData = [
  {
    unit: "第一单元",
    categories: [
      { group: "增长", words: [{en: "increase", cn: "增加"}, {en: "rise", cn: "上升"}, {en: "raise", cn: "提高"}, {en: "grow", cn: "生长，增长"}, {en: "growth", cn: "增加，增长"}, {en: "go up", cn: "上升，增长"}, {en: "boost", cn: "促进，增加"}, {en: "foster", cn: "养育，培养"}, {en: "boom", cn: "使兴旺，繁荣"}, {en: "promote", cn: "提升，促进"}, {en: "upgrade", cn: "提升，上升"}, {en: "greater", cn: "更大的"}, {en: "more", cn: "更多的"}, {en: "soar", cn: "猛增"}, {en: "extra", cn: "额外的"}, {en: "additional", cn: "额外的"}]},
      { group: "激起", words: [{en: "promote", cn: "提升，促进"}, {en: "improve", cn: "增进，增加"}, {en: "advance", cn: "促进，提升"}, {en: "prompt", cn: "促进，激起"}, {en: "initiate", cn: "开始，发起"}, {en: "encourage", cn: "鼓励，促进"}, {en: "boost", cn: "促进，增加"}, {en: "inspire", cn: "激发，产生"}, {en: "motivate", cn: "刺激"}, {en: "develop", cn: "开发，生长"}, {en: "irritate", cn: "刺激"}, {en: "incentive", cn: "激励，刺激"}, {en: "stimulate", cn: "激励，刺激"}, {en: "activate", cn: "触发"}, {en: "drive", cn: "驱动"}, {en: "enhance", cn: "提高，增加"}, {en: "prosper", cn: "使繁荣，使成功"}]},
      { group: "下降", words: [{en: "decrease", cn: "减少，减小"}, {en: "decline", cn: "下降，减少"}, {en: "reduce", cn: "减少，降低"}, {en: "reduction", cn: "减少，缩小"}, {en: "deduction", cn: "扣除，减除"}, {en: "fall", cn: "下降"}, {en: "downfall", cn: "下降"}, {en: "drop", cn: "下降"}, {en: "loss", cn: "亏损；减少"}, {en: "cut", cn: "减少，降低"}, {en: "diminish", cn: "变小；减少"}, {en: "shrink", cn: "收缩，缩减"}, {en: "alleviate", cn: "减轻，缓解"}, {en: "less", cn: "较少的, 更少的"}, {en: "lessen", cn: "减少；减轻"}, {en: "relief", cn: "减轻，解除"}]},
      { group: "削弱", words: [{en: "eliminate", cn: "消除, 排除"}, {en: "diminish", cn: "变小；减少"}, {en: "mitigate", cn: "减轻，缓和"}, {en: "vanish", cn: "使消失"}, {en: "disappear", cn: "消失"}, {en: "loss", cn: "亏损；减少"}, {en: "gone", cn: "离去的；用光的"}, {en: "decrease", cn: "减少，减小"}, {en: "eradicate", cn: "消灭，根除"}]},
      { group: "复杂的", words: [{en: "complex", cn: "复杂的"}, {en: "complicated", cn: "复杂的"}, {en: "sophisticated", cn: "复杂的；精密的"}, {en: "difficult", cn: "困难的，难懂的"}, {en: "harsh", cn: "严厉的；严酷的"}, {en: "tough", cn: "困难的"}, {en: "hard", cn: "困难的"}, {en: "elusive", cn: "难以捉摸的"}, {en: "demanding", cn: "费心费力的"}, {en: "complexity", cn: "复杂性"}, {en: "challenging", cn: "富有挑战性的"}, {en: "perplexing", cn: "使人困惑的"}, {en: "comprehensive", cn: "广泛的，综合的"}, {en: "intricacy", cn: "错综复杂；难以理解"}]},
      { group: "简单的", words: [{en: "facilitate", cn: "使便利，减轻困难"}, {en: "easy", cn: "容易的；不费力地"}, {en: "convenient", cn: "方便的, 便利的"}, {en: "straightforward", cn: "简单的；易懂的"}, {en: "simplicity", cn: "简单"}]},
      { group: "好处", words: [{en: "advantage", cn: "益处"}, {en: "benefit", cn: "有益于；益处"}, {en: "valuable", cn: "贵重的；有价值的"}, {en: "wholesome", cn: "有益健康的"}, {en: "helpful", cn: "有益的"}, {en: "beneficial", cn: "有益的, 有利的"}, {en: "advance", cn: "促进，提升"}, {en: "improvement", cn: "增加，改进"}, {en: "profit", cn: "有益；利益"}, {en: "useful", cn: "有用的；有帮助的"}, {en: "positive", cn: "积极的"}, {en: "effective", cn: "有效的"}, {en: "strength", cn: "长处"}, {en: "value", cn: "价值；有价值"}, {en: "usefulness", cn: "有用，有益"}, {en: "treasure", cn: "珍宝"}, {en: "precious", cn: "宝贵的，珍贵的"}]},
      { group: "坏处", words: [{en: "disadvantage", cn: "不利，劣势"}, {en: "shortcoming", cn: "短处，缺点"}, {en: "shortage", cn: "不足；缺少"}, {en: "weakness", cn: "弱点，缺点"}, {en: "drawback", cn: "缺点，不利条件"}, {en: "difficulty", cn: "困难，难度"}, {en: "trouble", cn: "麻烦；烦恼"}, {en: "troublesome", cn: "引起麻烦的"}, {en: "burden", cn: "负担"}, {en: "hurdle", cn: "障碍"}, {en: "problem", cn: "问题，难题"}, {en: "challenge", cn: "挑战，怀疑"}, {en: "challenging", cn: "富有挑战性的"}, {en: "demanding", cn: "费心费力的"}, {en: "hardship", cn: "艰难，困苦"}, {en: "obstacle", cn: "障碍，妨碍"}, {en: "barrier", cn: "障碍，阻碍"}, {en: "defect", cn: "缺点，缺陷；背叛"}, {en: "adversity", cn: "困境"}]},
      { group: "消极的", words: [{en: "negative", cn: "消极的"}, {en: "pessimistic", cn: "悲观的"}, {en: "passive", cn: "消极的"}, {en: "inactive", cn: "不活跃的"}]},
      { group: "重要的", words: [{en: "significant", cn: "重要的"}, {en: "important", cn: "重要的"}, {en: "crucial", cn: "重要的"}, {en: "vital", cn: "极重要的"}, {en: "chief", cn: "主要的，首要的"}, {en: "major", cn: "主要的；重要的"}, {en: "remarkable", cn: "异常的；引人注目的"}, {en: "essential", cn: "基本的，必要的"}, {en: "magnitude", cn: "重要性"}]},
      { group: "基本的", words: [{en: "fundamental", cn: "基本的，重要的"}, {en: "rudimentary", cn: "基本的, 初步的"}, {en: "preliminary", cn: "初步的，开端的"}, {en: "basic", cn: "基本的；基础的"}, {en: "essential", cn: "基本的，必要的"}, {en: "underlying", cn: "根本的, 基础的"}, {en: "underlie", cn: "构成…的基础"}, {en: "basis", cn: "基础"}, {en: "base", cn: "基础"}, {en: "ground", cn: "基础，根基"}, {en: "root", cn: "根源，根基"}, {en: "prime", cn: "基本的；主要的"}]},
      { group: "优先", words: [{en: "priority", cn: "优先"}, {en: "preference", cn: "优待"}, {en: "supreme", cn: "最高的；最重要的"}, {en: "supremacy", cn: "至高"}]},
      { group: "首先 首要", words: [{en: "primary", cn: "主要的基本的；初级的"}, {en: "leading", cn: "主要的"}, {en: "major", cn: "主要的；重要的"}, {en: "first", cn: "首先；优先"}, {en: "firstly", cn: "首先"}, {en: "original", cn: "原始的；最初的"}, {en: "initial", cn: "最初的"}, {en: "main", cn: "主要的，最重要的"}, {en: "principal", cn: "最重要的；主要的"}, {en: "paramount", cn: "最高的；首要的"}, {en: "primitive", cn: "原始的，早期的"}, {en: "origin", cn: "起点；来源"}]},
      { group: "统治", words: [{en: "dominant", cn: "统治的；占优势的"}, {en: "overbearing", cn: "专横的；压倒性的"}, {en: "overwhelming", cn: "势不可挡的，压倒一切的"}, {en: "major", cn: "主要的；重要的"}, {en: "predominant", cn: "占主导地位的, 显著的"}]},
      { group: "最后的", words: [{en: "eventually", cn: "终于, 最后"}, {en: "end", cn: "结束，终止"}, {en: "last", cn: "最后的，末尾的"}, {en: "final", cn: "最后的, 最终的"}, {en: "finally", cn: "终于；最后"}, {en: "finish", cn: "完成；结束"}]},
      { group: "持久的", words: [{en: "durable", cn: "耐用的，持久的"}, {en: "lasting", cn: "持久的；永恒的"}, {en: "chronic", cn: "慢性的；长期的"}, {en: "duration", cn: "持续"}, {en: "time", cn: "时间"}, {en: "period", cn: "时期"}]},
      { group: "每年", words: [{en: "annual", cn: "年度的；每年的"}, {en: "yearly", cn: "每年的"}]},
      { group: "不重要的", words: [{en: "trivial", cn: "不重要的"}, {en: "peripheral", cn: "非本质的；次要的"}, {en: "unimportant", cn: "不重要的，次要的"}, {en: "minor", cn: "少数的，次要的"}]},
      { group: "特别的", words: [{en: "extraordinary", cn: "非同寻常的"}, {en: "rare", cn: "稀有的，罕见的"}, {en: "unusual", cn: "不寻常的"}, {en: "scarce", cn: "缺乏的，罕见的"}, {en: "abnormal", cn: "反常的，异常的"}, {en: "remarkable", cn: "异常的；引人注目的"}, {en: "different", cn: "不同的，差异的"}, {en: "unique", cn: "独有的；独特的"}, {en: "special", cn: "特别的"}, {en: "exceptional", cn: "例外的；独特的"}, {en: "extreme", cn: "极端的；极度的"}, {en: "unexpected", cn: "意外的"}]}
    ]
  },
  {
    unit: "第二单元",
    categories: [
      { group: "一致", words: [{en: "agree", cn: "同意"}, {en: "consistent", cn: "一致的"}, {en: "accordance", cn: "一致"}, {en: "coherence", cn: "一致性"}, {en: "conform", cn: "符合，使一致"}, {en: "corresponding", cn: "相应的，一致的"}, {en: "harmony", cn: "和谐，一致"}, {en: "consensus", cn: "一致同意"}, {en: "compatible", cn: "兼容的，一致的"}]},
      { group: "同意", words: [{en: "approve", cn: "批准，同意"}, {en: "agree", cn: "同意"}, {en: "accept", cn: "接受"}, {en: "consent", cn: "同意"}, {en: "assent", cn: "同意"}, {en: "acquiesce", cn: "默认，默许"}, {en: "concur", cn: "同意"}]},
      { group: "允许", words: [{en: "allow", cn: "允许"}, {en: "permit", cn: "许可"}, {en: "enable", cn: "使能够"}, {en: "authorize", cn: "授权"}, {en: "empower", cn: "授权"}, {en: "facilitate", cn: "促进，使便利"}]},
      { group: "影响", words: [{en: "affect", cn: "影响"}, {en: "influence", cn: "影响"}, {en: "impact", cn: "影响"}, {en: "effect", cn: "效果，影响"}, {en: "result", cn: "结果"}, {en: "consequence", cn: "后果"}, {en: "outcome", cn: "结果"}, {en: "ramification", cn: "结果，影响"}]},
      { group: "提供", words: [{en: "provide", cn: "提供"}, {en: "supply", cn: "供应"}, {en: "offer", cn: "提供"}, {en: "furnish", cn: "提供"}, {en: "provide with", cn: "提供"}, {en: "supply with", cn: "供应"}, {en: "equip with", cn: "装备"}, {en: "endow with", cn: "赋予"}, {en: "provide for", cn: "为...提供"}]},
      { group: "产生", words: [{en: "produce", cn: "生产，产生"}, {en: "generate", cn: "产生"}, {en: "create", cn: "创造"}, {en: "bring about", cn: "导致"}, {en: "yield", cn: "产生"}, {en: "result in", cn: "导致"}, {en: "lead to", cn: "导致"}, {en: "cause", cn: "引起"}, {en: "engender", cn: "产生"}]},
      { group: "导致", words: [{en: "lead to", cn: "导致"}, {en: "result in", cn: "导致"}, {en: "cause", cn: "引起"}, {en: "bring about", cn: "导致"}, {en: "contribute to", cn: "促成"}, {en: "result from", cn: "由...产生"}, {en: "stem from", cn: "源于"}, {en: "originate from", cn: "起源于"}, {en: "derive from", cn: "源于"}]},
      { group: "改变", words: [{en: "change", cn: "改变"}, {en: "alter", cn: "改变"}, {en: "modify", cn: "修改"}, {en: "transform", cn: "转变"}, {en: "convert", cn: "转换"}, {en: "adjust", cn: "调整"}, {en: "adapt", cn: "适应，调整"}, {en: "modify", cn: "修改"}, {en: "revise", cn: "修订"}]},
      { group: "保持", words: [{en: "maintain", cn: "保持"}, {en: "preserve", cn: "保存"}, {en: "keep", cn: "保持"}, {en: "retain", cn: "保留"}, {en: "sustain", cn: "维持"}, {en: "continue", cn: "继续"}, {en: "persist", cn: "坚持"}, {en: "endure", cn: "持久"}, {en: "last", cn: "持续"}]},
      { group: "减少", words: [{en: "reduce", cn: "减少"}, {en: "decrease", cn: "减少"}, {en: "diminish", cn: "减少"}, {en: "lessen", cn: "减少"}, {en: "lower", cn: "降低"}, {en: "minimize", cn: "最小化"}, {en: "alleviate", cn: "减轻"}, {en: "mitigate", cn: "减轻"}, {en: "relieve", cn: "缓解"}]},
      { group: "增加", words: [{en: "increase", cn: "增加"}, {en: "raise", cn: "提高"}, {en: "enhance", cn: "增强"}, {en: "improve", cn: "改进"}, {en: "boost", cn: "提升"}, {en: "augment", cn: "增加"}, {en: "amplify", cn: "放大"}, {en: "intensify", cn: "加强"}, {en: "strengthen", cn: "加强"}]},
      { group: "解决", words: [{en: "solve", cn: "解决"}, {en: "resolve", cn: "解决"}, {en: "address", cn: "处理"}, {en: "tackle", cn: "解决"}, {en: "handle", cn: "处理"}, {en: "deal with", cn: "处理"}, {en: "cope with", cn: "应对"}, {en: "manage", cn: "管理"}, {en: "resolve", cn: "解决"}]},
      { group: "发展", words: [{en: "develop", cn: "发展"}, {en: "evolve", cn: "进化"}, {en: "progress", cn: "进步"}, {en: "advance", cn: "前进"}, {en: "grow", cn: "成长"}, {en: "expand", cn: "扩张"}, {en: "mature", cn: "成熟"}, {en: "flourish", cn: "繁荣"}, {en: "thrive", cn: "兴旺"}]},
      { group: "重要", words: [{en: "important", cn: "重要的"}, {en: "significant", cn: "重要的"}, {en: "crucial", cn: "关键的"}, {en: "vital", cn: "至关重要的"}, {en: "essential", cn: "必要的"}, {en: "fundamental", cn: "基础的"}, {en: "critical", cn: "关键的"}, {en: "paramount", cn: "最重要的"}, {en: "primary", cn: "主要的"}]},
      { group: "不同", words: [{en: "different", cn: "不同的"}, {en: "distinct", cn: "不同的"}, {en: "diverse", cn: "多样的"}, {en: "varied", cn: "多样的"}, {en: "various", cn: "各种的"}, {en: "differ", cn: "不同"}, {en: "distinguish", cn: "区分"}, {en: "discriminate", cn: "区分"}, {en: "contrast", cn: "对比"}]}
    ]
  },
  {
    unit: "第三单元",
    categories: [
      { group: "环境", words: [{en: "environment", cn: "环境"}, {en: "environmental", cn: "环境的"}, {en: "surroundings", cn: "环境"}, {en: "ambience", cn: "环境"}, {en: "atmosphere", cn: "氛围"}, {en: "ecosystem", cn: "生态系统"}, {en: "habitat", cn: "栖息地"}, {en: "nature", cn: "自然"}, {en: "ecology", cn: "生态学"}]},
      { group: "污染", words: [{en: "pollute", cn: "污染"}, {en: "pollution", cn: "污染"}, {en: "contaminate", cn: "污染"}, {en: "contamination", cn: "污染"}, {en: "emission", cn: "排放"}, {en: "discharge", cn: "排放"}, {en: "release", cn: "释放"}, {en: "emit", cn: "排放"}, {en: "pollutant", cn: "污染物"}]},
      { group: "能源", words: [{en: "energy", cn: "能源"}, {en: "power", cn: "电力"}, {en: "fuel", cn: "燃料"}, {en: "resource", cn: "资源"}, {en: "renewable", cn: "可再生的"}, {en: "non-renewable", cn: "不可再生的"}, {en: "solar", cn: "太阳能的"}, {en: "wind", cn: "风能的"}, {en: "hydro", cn: "水能的"}]},
      { group: "可持续发展", words: [{en: "sustainable", cn: "可持续的"}, {en: "sustainability", cn: "可持续性"}, {en: "eco-friendly", cn: "环保的"}, {en: "green", cn: "绿色的"}, {en: "environmentally friendly", cn: "环保的"}, {en: "conservation", cn: "保护"}, {en: "preservation", cn: "保存"}, {en: "recycle", cn: "回收"}, {en: "reuse", cn: "再利用"}]},
      { group: "气候", words: [{en: "climate", cn: "气候"}, {en: "weather", cn: "天气"}, {en: "global warming", cn: "全球变暖"}, {en: "climate change", cn: "气候变化"}, {en: "greenhouse effect", cn: "温室效应"}, {en: "carbon dioxide", cn: "二氧化碳"}, {en: "carbon footprint", cn: "碳足迹"}, {en: "emission", cn: "排放"}, {en: "pollution", cn: "污染"}]},
      { group: "资源", words: [{en: "resource", cn: "资源"}, {en: "natural resource", cn: "自然资源"}, {en: "finite resource", cn: "有限资源"}, {en: "infinite resource", cn: "无限资源"}, {en: "renewable resource", cn: "可再生资源"}, {en: "non-renewable resource", cn: "不可再生资源"}, {en: "scarce", cn: "稀缺的"}, {en: "abundant", cn: "丰富的"}, {en: "plentiful", cn: "充足的"}]},
      { group: "保护", words: [{en: "protect", cn: "保护"}, {en: "conservation", cn: "保护"}, {en: "preservation", cn: "保存"}, {en: "safeguard", cn: "保护"}, {en: "defend", cn: "保护"}, {en: "shield", cn: "保护"}, {en: "protect from", cn: "保护免受"}, {en: "conserve", cn: "保护"}, {en: "preserve", cn: "保存"}]},
      { group: "破坏", words: [{en: "destroy", cn: "破坏"}, {en: "damage", cn: "损害"}, {en: "harm", cn: "伤害"}, {en: "ruin", cn: "毁坏"}, {en: "devastate", cn: "摧毁"}, {en: "wreck", cn: "破坏"}, {en: "pollute", cn: "污染"}, {en: "contaminate", cn: "污染"}, {en: "degrade", cn: "退化"}]},
      { group: "生物多样性", words: [{en: "biodiversity", cn: "生物多样性"}, {en: "species", cn: "物种"}, {en: "ecosystem", cn: "生态系统"}, {en: "habitat", cn: "栖息地"}, {en: "extinct", cn: "灭绝的"}, {en: "endangered", cn: "濒危的"}, {en: "threatened", cn: "受威胁的"}, {en: "conservation", cn: "保护"}, {en: "preservation", cn: "保存"}]},
      { group: "环境问题", words: [{en: "environmental problem", cn: "环境问题"}, {en: "pollution", cn: "污染"}, {en: "climate change", cn: "气候变化"}, {en: "global warming", cn: "全球变暖"}, {en: "deforestation", cn: "森林砍伐"}, {en: "desertification", cn: "荒漠化"}, {en: "urbanization", cn: "城市化"}, {en: "overpopulation", cn: "人口过剩"}, {en: "resource depletion", cn: "资源枯竭"}]}
    ]
  },
  {
    unit: "第四单元",
    categories: [
      { group: "科技", words: [{en: "technology", cn: "技术"}, {en: "science", cn: "科学"}, {en: "scientific", cn: "科学的"}, {en: "technological", cn: "技术的"}, {en: "innovation", cn: "创新"}, {en: "invention", cn: "发明"}, {en: "discovery", cn: "发现"}, {en: "research", cn: "研究"}, {en: "development", cn: "发展"}]},
      { group: "创新", words: [{en: "innovate", cn: "创新"}, {en: "innovation", cn: "创新"}, {en: "creative", cn: "创造性的"}, {en: "creativity", cn: "创造力"}, {en: "invent", cn: "发明"}, {en: "invention", cn: "发明"}, {en: "original", cn: "原创的"}, {en: "novel", cn: "新颖的"}, {en: "breakthrough", cn: "突破"}]},
      { group: "互联网", words: [{en: "internet", cn: "互联网"}, {en: "web", cn: "网络"}, {en: "online", cn: "在线的"}, {en: "digital", cn: "数字的"}, {en: "virtual", cn: "虚拟的"}, {en: "cyber", cn: "网络的"}, {en: "website", cn: "网站"}, {en: "webpage", cn: "网页"}, {en: "e-commerce", cn: "电子商务"}]},
      { group: "计算机", words: [{en: "computer", cn: "计算机"}, {en: "laptop", cn: "笔记本电脑"}, {en: "desktop", cn: "台式电脑"}, {en: "tablet", cn: "平板电脑"}, {en: "smartphone", cn: "智能手机"}, {en: "software", cn: "软件"}, {en: "hardware", cn: "硬件"}, {en: "program", cn: "程序"}, {en: "application", cn: "应用"}]},
      { group: "通信", words: [{en: "communication", cn: "通信"}, {en: "communicate", cn: "交流"}, {en: "telecommunication", cn: "电信"}, {en: "network", cn: "网络"}, {en: "connect", cn: "连接"}, {en: "link", cn: "链接"}, {en: "contact", cn: "联系"}, {en: "message", cn: "消息"}, {en: "information", cn: "信息"}]},
      { group: "信息", words: [{en: "information", cn: "信息"}, {en: "data", cn: "数据"}, {en: "knowledge", cn: "知识"}, {en: "fact", cn: "事实"}, {en: "statistic", cn: "统计数据"}, {en: "figure", cn: "数字"}, {en: "number", cn: "数字"}, {en: "detail", cn: "细节"}, {en: "information technology", cn: "信息技术"}]},
      { group: "自动化", words: [{en: "automation", cn: "自动化"}, {en: "automatic", cn: "自动的"}, {en: "robot", cn: "机器人"}, {en: "artificial intelligence", cn: "人工智能"}, {en: "AI", cn: "人工智能"}, {en: "machine learning", cn: "机器学习"}, {en: "algorithm", cn: "算法"}, {en: "computer vision", cn: "计算机视觉"}, {en: "natural language processing", cn: "自然语言处理"}]},
      { group: "医疗科技", words: [{en: "medical technology", cn: "医疗科技"}, {en: "healthcare", cn: "医疗保健"}, {en: "medicine", cn: "医学"}, {en: "pharmaceutical", cn: "制药的"}, {en: "drug", cn: "药物"}, {en: "treatment", cn: "治疗"}, {en: "therapy", cn: "疗法"}, {en: "diagnosis", cn: "诊断"}, {en: "surgery", cn: "手术"}]},
      { group: "航天科技", words: [{en: "space technology", cn: "航天科技"}, {en: "astronomy", cn: "天文学"}, {en: "space exploration", cn: "太空探索"}, {en: "satellite", cn: "卫星"}, {en: "rocket", cn: "火箭"}, {en: "shuttle", cn: "航天飞机"}, {en: "space station", cn: "空间站"}, {en: "astronaut", cn: "宇航员"}, {en: "cosmonaut", cn: "宇航员"}]},
      { group: "军事科技", words: [{en: "military technology", cn: "军事科技"}, {en: "defense", cn: "国防"}, {en: "weapon", cn: "武器"}, {en: "army", cn: "军队"}, {en: "navy", cn: "海军"}, {en: "air force", cn: "空军"}, {en: "missile", cn: "导弹"}, {en: "nuclear", cn: "核的"}, {en: "warfare", cn: "战争"}]}
    ]
  },
  {
    unit: "第五单元",
    categories: [
      { group: "健康", words: [{en: "health", cn: "健康"}, {en: "healthy", cn: "健康的"}, {en: "wellness", cn: "健康"}, {en: "well-being", cn: "健康"}, {en: "fitness", cn: "健康"}, {en: "physical health", cn: "身体健康"}, {en: "mental health", cn: "心理健康"}, {en: "emotional health", cn: "情绪健康"}, {en: "healthy lifestyle", cn: "健康生活方式"}]},
      { group: "疾病", words: [{en: "disease", cn: "疾病"}, {en: "illness", cn: "疾病"}, {en: "sickness", cn: "疾病"}, {en: "ailment", cn: "疾病"}, {en: "disorder", cn: "紊乱"}, {en: "condition", cn: "状况"}, {en: "symptom", cn: "症状"}, {en: "syndrome", cn: "综合征"}, {en: "infection", cn: "感染"}]},
      { group: "医疗", words: [{en: "medical", cn: "医疗的"}, {en: "medicine", cn: "医学"}, {en: "healthcare", cn: "医疗保健"}, {en: "hospital", cn: "医院"}, {en: "clinic", cn: "诊所"}, {en: "doctor", cn: "医生"}, {en: "nurse", cn: "护士"}, {en: "treatment", cn: "治疗"}, {en: "therapy", cn: "疗法"}]},
      { group: "心理", words: [{en: "psychology", cn: "心理学"}, {en: "psychological", cn: "心理的"}, {en: "mental", cn: "心理的"}, {en: "emotional", cn: "情绪的"}, {en: "psychiatric", cn: "精神的"}, {en: "therapy", cn: "疗法"}, {en: "counseling", cn: "咨询"}, {en: "psychotherapy", cn: "心理治疗"}, {en: "mental health", cn: "心理健康"}]},
      { group: "营养", words: [{en: "nutrition", cn: "营养"}, {en: "nutritional", cn: "营养的"}, {en: "diet", cn: "饮食"}, {en: "food", cn: "食物"}, {en: "healthy diet", cn: "健康饮食"}, {en: "balanced diet", cn: "均衡饮食"}, {en: "nutritionist", cn: "营养师"}, {en: "dietitian", cn: "营养师"}, {en: "calorie", cn: "卡路里"}]},
      { group: "运动", words: [{en: "exercise", cn: "运动"}, {en: "physical activity", cn: "身体活动"}, {en: "sport", cn: "运动"}, {en: "fitness", cn: "健康"}, {en: "workout", cn: "锻炼"}, {en: "training", cn: "训练"}, {en: "athletic", cn: "运动的"}, {en: "active", cn: "活跃的"}, {en: "fit", cn: "健康的"}]},
      { group: "睡眠", words: [{en: "sleep", cn: "睡眠"}, {en: "sleeping", cn: "睡眠的"}, {en: "sleep quality", cn: "睡眠质量"}, {en: "insomnia", cn: "失眠"}, {en: "sleep deprivation", cn: "睡眠不足"}, {en: "nap", cn: "小睡"}, {en: "rest", cn: "休息"}, {en: "relaxation", cn: "放松"}, {en: "sleep disorder", cn: "睡眠障碍"}]},
      { group: "压力", words: [{en: "stress", cn: "压力"}, {en: "stressful", cn: "有压力的"}, {en: "pressure", cn: "压力"}, {en: "tension", cn: "紧张"}, {en: "anxiety", cn: "焦虑"}, {en: "worry", cn: "担忧"}, {en: "concern", cn: "关注"}, {en: "stress management", cn: "压力管理"}, {en: "relaxation", cn: "放松"}]},
      { group: "药物", words: [{en: "drug", cn: "药物"}, {en: "medicine", cn: "药物"}, {en: "medication", cn: "药物"}, {en: "pill", cn: "药片"}, {en: "tablet", cn: "药片"}, {en: "capsule", cn: "胶囊"}, {en: "injection", cn: "注射"}, {en: "vaccine", cn: "疫苗"}, {en: "antibiotic", cn: "抗生素"}]},
      { group: "公共卫生", words: [{en: "public health", cn: "公共卫生"}, {en: "health policy", cn: "健康政策"}, {en: "health promotion", cn: "健康促进"}, {en: "disease prevention", cn: "疾病预防"}, {en: "epidemic", cn: "流行病"}, {en: "pandemic", cn: "大流行病"}, {en: "health education", cn: "健康教育"}, {en: "health awareness", cn: "健康意识"}, {en: "health campaign", cn: "健康运动"}]}
    ]
  },
  {
    unit: "第六单元",
    categories: [
      { group: "课程", words: [{en: "lecture", cn: "演讲；讲课"}, {en: "curriculum", cn: "总课程"}, {en: "syllabus", cn: "教学大纲；课程表"}, {en: "course", cn: "课程"}]},
      { group: "能力", words: [{en: "expertise", cn: "专门知识，技能"}, {en: "skill", cn: "技能，技巧；技术"}, {en: "knowledge", cn: "了解，理解"}, {en: "capable", cn: "能干的，有能力的；有才华的"}, {en: "capacity", cn: "能力；容量"}, {en: "ability", cn: "能力；力量"}, {en: "competence", cn: "能力，技能"}, {en: "faculty", cn: "全体教员；能力，才能"}, {en: "capability", cn: "能力"}]},
      { group: "容量", words: [{en: "volume", cn: "容量；体积"}, {en: "capacity", cn: "能力；容量"}]},
      { group: "参与", words: [{en: "involve", cn: "参与；牵扯；包含"}, {en: "join", cn: "参加；连接；结合"}, {en: "take part in", cn: "参加"}, {en: "participate", cn: "参加，参与"}, {en: "associate", cn: "联合"}]},
      { group: "关联", words: [{en: "link", cn: "联系，关系，连接"}, {en: "connect", cn: "连接；联合；关连"}, {en: "correlation", cn: "相互的关系"}, {en: "reflect", cn: "反射，反映"}, {en: "relate", cn: "联系起来"}, {en: "associate", cn: "联合"}, {en: "join", cn: "参加；连接；结合"}, {en: "attach", cn: "固定；附着，缠着"}, {en: "connection", cn: "连接，联系"}, {en: "relation", cn: "关系；亲属关系"}, {en: "relative", cn: "相对的；有关系的"}, {en: "relevant", cn: "有关的，切题的"}]},
      { group: "整合", words: [{en: "integration", cn: "整合，混合；一体化"}, {en: "combine", cn: "联合"}, {en: "whole", cn: "整体的，全部的"}, {en: "entire", cn: "全部的，整个的"}, {en: "cumulative", cn: "累积的，渐增的"}, {en: "put together", cn: "组成整体"}, {en: "reinforce", cn: "增强；加强"}, {en: "integrity", cn: "整合，完全；诚实"}, {en: "integral", cn: "构成整体所必需的"}, {en: "mixture", cn: "混合；混合物"}, {en: "hybrid", cn: "混合的；杂交的"}, {en: "combination", cn: "结合，组合"}, {en: "integrate", cn: "结合成为整体；融入"}]},
      { group: "一致的", words: [{en: "consistent", cn: "一贯的，一致的，符合的"}, {en: "uniform", cn: "一律的，全都相同的"}, {en: "compatible", cn: "可以并存的，协调的"}, {en: "persistent", cn: "持续的；不断的"}, {en: "constant", cn: "始终如一的；不断的"}, {en: "corresponding", cn: "符合的，一致的；对应的"}, {en: "accordance", cn: "一致，和谐，符合"}, {en: "conform", cn: "符合，使一致，遵守"}, {en: "coherence", cn: "连贯性，一致性"}, {en: "persistent", cn: "持续的；不断的"}, {en: "uniform", cn: "一律的，全都相同的"}, {en: "stable", cn: "稳定的；牢固的"}, {en: "unchanged", cn: "无变化的"}, {en: "stability", cn: "稳定，稳固"}]},
      { group: "矛盾的", words: [{en: "incompatible", cn: "不协调的，不相配的"}, {en: "contradictory", cn: "矛盾的"}, {en: "paradox", cn: "矛盾，相悖"}, {en: "inconsistent", cn: "不一致的，不协调的"}, {en: "disputable", cn: "有争议的"}, {en: "controversial", cn: "有争议的"}]},
      { group: "合作和谐的", words: [{en: "cooperative", cn: "合作的，协作的"}, {en: "cooperation", cn: "合作"}, {en: "coordinate", cn: "协调，协作"}, {en: "harmony", cn: "协调；和谐"}, {en: "work together", cn: "一起工作"}, {en: "support", cn: "支撑；支持"}, {en: "coordination", cn: "协调，和谐"}, {en: "team", cn: "合作"}, {en: "teamwork", cn: "团队合作"}, {en: "mediation", cn: "调解，调停"}, {en: "interaction", cn: "合作；相互作用"}]},
      { group: "冲突干涉", words: [{en: "conflict", cn: "冲突，斗争"}, {en: "compete", cn: "竞赛；竞争"}, {en: "intervention", cn: "介入，干涉，干预"}, {en: "interference", cn: "干涉，介入"}]},
      { group: "暴力侵犯", words: [{en: "violent", cn: "暴力的，粗暴的；剧烈的"}, {en: "fierce", cn: "凶猛的；暴躁的；猛烈的"}, {en: "aggressive", cn: "好斗的，挑衅的，侵略的"}, {en: "violate", cn: "侵犯；违反"}, {en: "attack", cn: "攻击，进攻；抨击"}]}
    ]
  },
  {
    unit: "第七单元",
    categories: [
      { group: "动物", words: [{en: "mammal", cn: "哺乳动物"}, {en: "creature", cn: "动物，生物"}, {en: "species", cn: "物种；种类"}, {en: "animal", cn: "动物"}, {en: "wildlife", cn: "野生动植物"}]},
      { group: "观众", words: [{en: "audience", cn: "观众；听众"}, {en: "reader", cn: "读者"}, {en: "visitor", cn: "参观者，访问者"}, {en: "viewer", cn: "观看者；观众"}]},
      { group: "吃", words: [{en: "prey", cn: "捕食；掠夺"}, {en: "feed", cn: "吃；喂养"}, {en: "eat", cn: "吃"}, {en: "consume", cn: "消耗；吃喝"}]},
      { group: "交换", words: [{en: "exchange", cn: "交换；交易"}, {en: "share", cn: "分享"}, {en: "interchange", cn: "交换，互换"}]},
      { group: "识别", words: [{en: "identify", cn: "认出，识别"}, {en: "recognise", cn: "认出，识别，承认"}, {en: "perceive", cn: "感觉；理解；认知"}, {en: "acknowledge", cn: "承认，供认，鸣谢"}, {en: "realise", cn: "认识到；实现"}, {en: "appreciate", cn: "赏识；感激；体会"}, {en: "admit", cn: "承认，许可"}, {en: "comprehend", cn: "理解，领会"}, {en: "understand", cn: "懂；理解"}, {en: "know", cn: "知道；懂得"}, {en: "identify", cn: "认出，识别"}, {en: "interpret", cn: "解释，说明"}, {en: "ascertain", cn: "查明，弄清"}]},
      { group: "意识", words: [{en: "aware", cn: "意识到的；知道的"}, {en: "know", cn: "知道；懂得"}, {en: "conscious", cn: "意识到的，注意到的"}, {en: "awareness", cn: "察觉，意识"}, {en: "understand", cn: "懂；理解"}, {en: "discover", cn: "发现"}, {en: "realise", cn: "认识到；实现"}]},
      { group: "种类", words: [{en: "category", cn: "种类，类别"}, {en: "type", cn: "类型；种类"}]},
      { group: "显示揭露", words: [{en: "display", cn: "显示，显露；展览"}, {en: "show", cn: "显示，显露"}, {en: "demonstrate", cn: "显示，证明；游行"}, {en: "indicate", cn: "指出；象征"}, {en: "reveal", cn: "显示；露出；揭露"}, {en: "suggest", cn: "提议，建议"}, {en: "uncover", cn: "揭露；发现；揭示"}, {en: "illustrate", cn: "说明，阐明；表明"}, {en: "elaborate", cn: "说明"}, {en: "interpretation", cn: "解释，说明；诠释"}, {en: "disclose", cn: "揭露；公开"}, {en: "expose", cn: "揭露，揭发；显示"}, {en: "exposure", cn: "暴露，显露，揭发"}, {en: "refer to", cn: "指的是，参考"}, {en: "manifest", cn: "证明，表明；显示"}, {en: "obvious", cn: "明显的，显而易见的"}]},
      { group: "秘密的", words: [{en: "confidential", cn: "秘密的，机密的"}, {en: "undisclosed", cn: "未公开的；秘密的"}, {en: "secret", cn: "秘密"}, {en: "hidden", cn: "隐藏的"}]},
      { group: "先天遗传", words: [{en: "inherent", cn: "固有的，内在的；与生俱来的"}, {en: "inherit", cn: "继承；遗传"}, {en: "gene", cn: "基因"}, {en: "DNA", cn: "遗传因子"}, {en: "nature", cn: "本性；自然"}, {en: "innate", cn: "先天的；固有的；与生俱来的"}, {en: "built-in", cn: "内置的，内在的，先天的"}, {en: "inborn", cn: "天生的；先天的"}, {en: "heredity", cn: "遗传"}, {en: "instinct", cn: "天性；本能，直觉"}, {en: "intrinsic", cn: "固有的，内在的；本质的"}, {en: "natural", cn: "自然的，天然的，天生的"}, {en: "essential", cn: "基本的，必要的"}, {en: "basic", cn: "基本的；基础的"}, {en: "essence", cn: "本质，实质"}, {en: "genetic", cn: "遗传的；起源的；基因的"}]},
      { group: "后天培养", words: [{en: "nurture", cn: "养育；培育，培养"}, {en: "breed", cn: "繁殖；养殖"}, {en: "reproduce", cn: "繁殖，复制"}, {en: "cultivate", cn: "人工种植"}, {en: "grow", cn: "生长，增长"}, {en: "foster", cn: "养育，培养"}, {en: "environment", cn: "环境，周围状况"}]},
      { group: "仅仅只有", words: [{en: "solely", cn: "唯一地，仅仅"}, {en: "alone", cn: "单独的；孤独的；独自的"}, {en: "only", cn: "仅仅；唯一的"}, {en: "exclusive", cn: "独有的；高级的"}, {en: "merely", cn: "仅仅，只不过；只是"}, {en: "purely", cn: "纯粹地；仅仅，只不过"}, {en: "mainly", cn: "主要地，大体上"}]},
      { group: "灭绝", words: [{en: "extinct", cn: "灭绝的"}, {en: "die out", cn: "消失，灭绝"}, {en: "lost", cn: "失去的，消失的"}]},
      { group: "农业", words: [{en: "agriculture", cn: "农业"}, {en: "farm", cn: "农场，农业"}, {en: "farming", cn: "农事，耕作；畜牧业"}]},
      { group: "全球的", words: [{en: "global", cn: "全球的，全世界的；整体的"}, {en: "earth", cn: "地球；尘土"}, {en: "world", cn: "世界"}, {en: "worldwide", cn: "全世界的"}, {en: "international", cn: "国际的"}, {en: "this planet", cn: "这个星球，地球"}, {en: "overseas", cn: "在海外，海外"}]},
      { group: "充足的", words: [{en: "adequate", cn: "充分的，足够的"}, {en: "enough", cn: "足够的，充足的"}, {en: "abundance", cn: "充足；大量"}, {en: "sufficient", cn: "足够的；充足的"}, {en: "sufficiency", cn: "充足"}]},
      { group: "提供", words: [{en: "grant", cn: "授予"}, {en: "confer", cn: "授予，给予；协商"}, {en: "offer", cn: "提供"}]},
      { group: "老旧的", words: [{en: "old", cn: "年老的；古老的"}, {en: "elderly", cn: "上了年纪的"}, {en: "ancient", cn: "古代的；古老的"}, {en: "aged", cn: "老的；陈年的"}, {en: "past", cn: "过去；往事；经过"}, {en: "history", cn: "历史"}, {en: "previous", cn: "以前的；早先的；过早的"}]},
      { group: "拒绝", words: [{en: "reject", cn: "拒绝；抵制"}, {en: "turn down", cn: "拒绝"}, {en: "deny", cn: "否认；拒绝"}, {en: "reluctant", cn: "不情愿的，勉强的"}, {en: "unwilling", cn: "不愿意的；不情愿的"}, {en: "exclude", cn: "排斥；拒绝；排除"}]},
      { group: "同意", words: [{en: "consent", cn: "准许，同意，赞成"}, {en: "concur", cn: "一致；同意"}, {en: "agree", cn: "同意；赞成"}, {en: "approve", cn: "批准；赞成"}]},
      { group: "相似的", words: [{en: "resemble", cn: "像…，类似"}, {en: "similar", cn: "相似的"}, {en: "like", cn: "相似的"}]},
      { group: "方向定位", words: [{en: "orientation", cn: "方向；定位"}, {en: "direction", cn: "方向，动向"}, {en: "navigation", cn: "导航，领航；航行"}, {en: "positioning", cn: "配置，布置"}, {en: "situate", cn: "使位于；使处于"}]},
      { group: "焦虑紧张", words: [{en: "tension", cn: "紧张不安；张力，拉力"}, {en: "nervous", cn: "害怕的；紧张的"}, {en: "upset", cn: "心烦的；混乱的"}, {en: "anxious", cn: "担忧的；焦虑的；急切的"}, {en: "anxiety", cn: "焦虑；挂念"}, {en: "stress", cn: "压力；紧张"}]},
      { group: "抑郁", words: [{en: "depression", cn: "抑郁；大萧条"}, {en: "frustration", cn: "沮丧；挫折"}]},
      { group: "证明验证", words: [{en: "confirm", cn: "确认；批准；证实"}, {en: "verify", cn: "核实；查证"}, {en: "certify", cn: "证明，证实"}, {en: "identify", cn: "认出，识别"}, {en: "authenticate", cn: "证明是真实的；使生效"}, {en: "test", cn: "检验；测试"}]},
      { group: "保证", words: [{en: "guarantee", cn: "保证；担保"}, {en: "ensure", cn: "保证，确保"}, {en: "assurance", cn: "保证，担保，确信"}, {en: "assure", cn: "保证；担保；使确信"}]},
      { group: "死亡相关", words: [{en: "mortality", cn: "死亡率"}, {en: "death", cn: "死；死亡"}, {en: "bone", cn: "骨；骨骼"}, {en: "remains", cn: "遗骸，尸骨"}, {en: "skeleton", cn: "骨架，骨骼"}]},
      { group: "忽略", words: [{en: "ignore", cn: "忽视，不理睬"}, {en: "neglect", cn: "疏忽，忽视；忽略"}, {en: "underestimate", cn: "低估"}, {en: "overlook", cn: "俯瞰；忽略"}]},
      { group: "夸大", words: [{en: "exaggerate", cn: "夸大，夸张"}, {en: "overstate", cn: "夸大"}]},
      { group: "移除", words: [{en: "remove", cn: "移除；搬离"}, {en: "removed", cn: "远离的，隔绝的"}, {en: "get rid of", cn: "除掉，去掉"}, {en: "leave", cn: "离开；留下"}, {en: "no longer", cn: "不再"}, {en: "take away", cn: "带走，拿走，取走"}]},
      { group: "预测", words: [{en: "predict", cn: "预言；预知"}, {en: "expect", cn: "预料；预期"}, {en: "prophecy", cn: "预言"}, {en: "conjecture", cn: "推测；猜想"}, {en: "anticipate", cn: "预感, 期望"}]},
      { group: "随意的", words: [{en: "random", cn: "随机的；随意的"}, {en: "unpredictable", cn: "不可预测的；捉摸不透的"}, {en: "erratically", cn: "不规律地"}]},
      { group: "举例", words: [{en: "instance", cn: "例子，实例"}, {en: "such as", cn: "例如"}, {en: "including", cn: "包括，包含"}, {en: "for example", cn: "例如"}, {en: "for instance", cn: "例如"}, {en: "e.g.", cn: "for example 例如"}, {en: "i.e.", cn: "即，换言之"}]},
      { group: "假设假定", words: [{en: "hypothesis", cn: "假说，假设，前提"}, {en: "assumption", cn: "假定，假设"}, {en: "assume", cn: "假定；采取"}]}
    ]
  },
  {
    unit: "第八单元",
    categories: [
      { group: "官方机构", words: [{en: "authority", cn: "当局；权威"}, {en: "official", cn: "行政官员；官方的"}, {en: "council", cn: "地方议会"}, {en: "government", cn: "政府；治理"}, {en: "ministry", cn: "部门"}]},
      { group: "破坏", words: [{en: "collapse", cn: "倒塌；失败"}, {en: "destroy", cn: "毁坏；破坏；消灭"}, {en: "ruin", cn: "破坏，毁掉；废墟"}, {en: "breakdown", cn: "损坏，故障"}, {en: "malfunction", cn: "故障，障碍"}, {en: "disrupt", cn: "使混乱，扰乱"}, {en: "devastate", cn: "毁坏；压垮"}, {en: "wreck", cn: "破坏；使失事；拆毁"}, {en: "crash", cn: "碰撞；崩溃；坠落"}, {en: "blight", cn: "破坏；枯萎"}, {en: "wipe out", cn: "消灭，彻底摧毁"}, {en: "damage", cn: "损害，毁坏"}, {en: "break", cn: "打破；中断；休息"}, {en: "hurt", cn: "疼痛，痛苦；受伤"}, {en: "harm", cn: "损害，危害"}, {en: "spoil", cn: "损坏；毁掉；溺爱"}, {en: "injure", cn: "受伤"}, {en: "wound", cn: "伤害，受伤"}, {en: "detrimental", cn: "有害的，不利的"}, {en: "side effect", cn: "副作用"}, {en: "disturb", cn: "打扰；妨碍"}, {en: "impair", cn: "损害，削弱"}, {en: "erode", cn: "侵蚀，损害"}, {en: "erosion", cn: "腐蚀，侵蚀"}, {en: "rust", cn: "生锈，侵蚀"}]},
      { group: "灾难", words: [{en: "disaster", cn: "不幸；灾难，灾祸"}, {en: "catastrophe", cn: "灾祸，灾难"}, {en: "calamity", cn: "灾祸，灾难"}]},
      { group: "选择", words: [{en: "select", cn: "选择；挑选"}, {en: "option", cn: "选择权；选项"}, {en: "choice", cn: "选择；选择权"}]},
      { group: "概率可能性", words: [{en: "opportunity", cn: "机会，时机"}, {en: "chance", cn: "可能性；机会；冒……险"}, {en: "possibility", cn: "可能性"}, {en: "probability", cn: "可能性，概率"}, {en: "likelihood", cn: "可能性"}, {en: "potential", cn: "潜在的，有可能的，可能性"}, {en: "choice", cn: "选择；选择权"}, {en: "option", cn: "选择权；选项"}]},
      { group: "转折让步", words: [{en: "whereas", cn: "但是，然而"}, {en: "while", cn: "虽然；然而"}, {en: "but", cn: "但是；然而；仅仅"}, {en: "yet", cn: "然而；但是；还"}, {en: "however", cn: "然而，可是"}, {en: "though", cn: "可是，虽然，然而"}, {en: "although", cn: "虽然，尽管"}, {en: "albeit", cn: "即使；虽然"}, {en: "notwithstanding", cn: "尽管；然而"}, {en: "nonetheless", cn: "虽然如此，但是"}, {en: "nevertheless", cn: "尽管如此，然而"}]},
      { group: "一双", words: [{en: "couple", cn: "伴侣；一双，几个"}, {en: "mate", cn: "同事；伴侣"}, {en: "spouse", cn: "配偶"}, {en: "courtship", cn: "求爱期"}, {en: "double", cn: "双的；两倍"}, {en: "a pair of", cn: "一对，一双"}, {en: "two", cn: "两个；两个的"}, {en: "twice", cn: "两倍；两次"}]},
      { group: "自动化", words: [{en: "automatically", cn: "自动地"}, {en: "automation", cn: "自动化"}, {en: "robot", cn: "机器人，自动机械"}, {en: "artificial", cn: "人造的，人工的"}, {en: "artificial intelligence (AI)", cn: "人工智能"}, {en: "man-made", cn: "人造的，人工的；合成的"}, {en: "synthetic", cn: "合成的，人造的"}, {en: "automated", cn: "自动化的"}, {en: "autonomy", cn: "自治，自治权"}, {en: "independently", cn: "独立地，自立地"}]},
      { group: "暗示", words: [{en: "implicit", cn: "暗示的；含蓄的"}, {en: "implication", cn: "暗示；牵连；含义"}, {en: "imply", cn: "暗示；意味；隐含"}]},
      { group: "明确的", words: [{en: "explicit", cn: "详述的，明确的，明晰的"}, {en: "clear", cn: "清楚的"}, {en: "clarity", cn: "清楚，明晰"}, {en: "definite", cn: "明确的，确切的"}]},
      { group: "模糊的", words: [{en: "ambiguous", cn: "模棱两可的，含糊不清的"}, {en: "obscure", cn: "模糊的；晦涩的"}, {en: "hide", cn: "隐藏，隐瞒"}, {en: "conceal", cn: "隐藏；隐瞒"}, {en: "contingent", cn: "偶然的；依情况而变的"}, {en: "uncertain", cn: "不确定的；不确信的；模糊的"}]},
      { group: "具体的", words: [{en: "specific", cn: "特殊的，特定的；明确的"}, {en: "particular", cn: "特定的，特别的"}, {en: "exact", cn: "精确的；准确的"}, {en: "certain", cn: "肯定；某些"}, {en: "especially", cn: "尤其，特别"}, {en: "in particular", cn: "尤其，特别"}, {en: "specifically", cn: "特定地；明确地"}, {en: "mainly", cn: "主要地，大体上"}, {en: "particularly", cn: "特别；尤其"}, {en: "detailed", cn: "详细的，精细的，详尽的"}]},
      { group: "评估", words: [{en: "evaluation", cn: "估价，评价；估算"}, {en: "measure", cn: "测量；估量"}, {en: "calculate", cn: "计算，估计"}, {en: "assess", cn: "评定；估价"}, {en: "assessment", cn: "评估，评定；估价"}]},
      { group: "特性", words: [{en: "feature", cn: "特色，特征"}, {en: "trait", cn: "个性，特征，特点"}, {en: "property", cn: "财产；性质"}, {en: "characteristic", cn: "特征"}, {en: "factor", cn: "因素；要素"}]},
      { group: "延迟", words: [{en: "postpone", cn: "延期，延迟"}, {en: "delay", cn: "耽搁；延期"}, {en: "late", cn: "迟的，晚的"}, {en: "lag", cn: "迟延；落后"}]},
      { group: "文件", words: [{en: "document", cn: "文件，文档"}, {en: "documentation", cn: "文件记录；证据"}, {en: "record", cn: "记录；唱片"}, {en: "write down", cn: "写下，记下"}, {en: "log", cn: "记录；伐木"}]},
      { group: "项目", words: [{en: "initiative", cn: "倡议；主动"}, {en: "scheme", cn: "计划方案"}, {en: "plan", cn: "计划，打算"}, {en: "proposal", cn: "提议，建议"}, {en: "program", cn: "项目，程序；计划"}, {en: "scheme", cn: "计划方案"}, {en: "project", cn: "项目，方案，规划"}, {en: "issue", cn: "问题"}, {en: "topic", cn: "题目，论题，话题"}]},
      { group: "印象深刻的", words: [{en: "dramatic", cn: "引人注目的"}, {en: "impressive", cn: "给人印象深刻的"}, {en: "touching", cn: "动人的"}, {en: "striking", cn: "显著的，引人注目的"}, {en: "surprising", cn: "使人惊讶的，出人意料的"}, {en: "unexpected", cn: "意外的"}]},
      { group: "顺序", words: [{en: "sequence", cn: "先后次序，顺序，连续"}, {en: "array", cn: "排列，列阵"}, {en: "order", cn: "顺序，命令，订单"}, {en: "queue", cn: "排队，队列"}]},
      { group: "可能", words: [{en: "estimate", cn: "估计，估价"}, {en: "probably", cn: "大概，或许，可能"}, {en: "may", cn: "可能，可以；愿意"}]},
      { group: "尝试", words: [{en: "attempt", cn: "试图；尝试"}, {en: "try", cn: "尝试，试验"}, {en: "test", cn: "检验；测试"}]},
      { group: "获得", words: [{en: "obtain", cn: "获得"}, {en: "get", cn: "获得；得到"}, {en: "gain", cn: "获得，收获"}]},
      { group: "协会", words: [{en: "institute", cn: "协会，学院"}, {en: "association", cn: "协会，社团，联合"}, {en: "union", cn: "联合；联盟，协会"}]},
      { group: "超过", words: [{en: "exceed", cn: "超过；超越；突出"}, {en: "overtake", cn: "赶上；压倒；超车"}, {en: "surpass", cn: "胜过，优于；超越"}, {en: "excel", cn: "擅长；优于，胜过"}, {en: "transcend", cn: "超出，超越"}]},
      { group: "奇怪的", words: [{en: "odd", cn: "奇怪的；奇数的"}, {en: "suspicious", cn: "猜疑的，疑心的"}, {en: "strange", cn: "陌生的；奇怪的"}]},
      { group: "替代", words: [{en: "substitution", cn: "取代，代替，替代物"}, {en: "replace", cn: "取代，代替"}, {en: "supersede", cn: "取代，接替"}, {en: "alternative", cn: "二选一的；替代品"}, {en: "displacement", cn: "代替"}]},
      { group: "评论", words: [{en: "comment", cn: "评论"}, {en: "remark", cn: "话语，评论"}, {en: "review", cn: "评论；回顾；检查"}]},
      { group: "贡献", words: [{en: "contribution", cn: "捐助，贡献"}, {en: "donate", cn: "捐赠；捐献"}, {en: "dedicate", cn: "致力；献身"}, {en: "contribute", cn: "捐献，贡献"}]},
      { group: "自由", words: [{en: "liberal", cn: "自由主义的"}, {en: "liberty", cn: "自由"}, {en: "freedom", cn: "自由"}, {en: "free", cn: "自由的；免费的"}]},
      { group: "效用", words: [{en: "utility", cn: "功用，效用"}, {en: "utilisation", cn: "利用"}, {en: "application", cn: "申请，应用"}, {en: "use", cn: "使用；利用"}]},
      { group: "评分等级", words: [{en: "grade", cn: "等级，分数，程度"}, {en: "rank", cn: "等级；队列；排列"}, {en: "measure", cn: "测量；估量"}, {en: "rate", cn: "比率，速度，费率"}]},
      { group: "终极的", words: [{en: "ultimate", cn: "最后的，最终的"}, {en: "optimum", cn: "最适宜的，最佳情况"}, {en: "best", cn: "最好的；最愉快的；最合适的"}, {en: "most", cn: "最…"}]},
      { group: "补充", words: [{en: "complement", cn: "补充"}, {en: "provision", cn: "供给；准备；供给品"}, {en: "supplementary", cn: "增补的，补充的"}]},
      { group: "高强度的", words: [{en: "intensive", cn: "加强的，集中的，密集的"}, {en: "intense", cn: "强烈的；紧张的"}, {en: "strong", cn: "强壮的，坚强的，坚固的"}]},
      { group: "加强", words: [{en: "reinforce", cn: "增强；加强"}, {en: "strong", cn: "强壮的，坚强的，坚固的"}, {en: "strengthen", cn: "加强，巩固"}]}
    ]
  },
  {
    unit: "第九单元",
    categories: [
      { group: "能量能力", words: [{en: "energy", cn: "精力；能量"}, {en: "force", cn: "力量；武力"}, {en: "power", cn: "能力；力量；势力"}, {en: "push", cn: "推，推动，施压"}, {en: "enforce", cn: "实施，执行，强迫"}, {en: "dynamic", cn: "动态的；动力的"}]},
      { group: "海洋", words: [{en: "marine", cn: "海的"}, {en: "sea", cn: "海洋"}, {en: "ocean", cn: "海洋"}, {en: "water", cn: "水"}]},
      { group: "实习见习", words: [{en: "practitioner", cn: "实习者"}, {en: "intern", cn: "实习生"}, {en: "apprentice", cn: "学徒"}, {en: "apprenticeship", cn: "学徒身份"}]},
      { group: "偏见", words: [{en: "bias", cn: "偏见"}, {en: "biased", cn: "有偏见的"}]},
      { group: "公平", words: [{en: "equal", cn: "相等的，平等的"}, {en: "fair", cn: "公平的"}, {en: "even", cn: "公平的；甚至"}, {en: "unbiased", cn: "无偏见的；公正的"}]},
      { group: "赞扬", words: [{en: "credit", cn: "赞扬；信用；学分"}, {en: "praise", cn: "称赞；赞扬"}, {en: "commend", cn: "表扬；称赞"}]},
      { group: "批评", words: [{en: "critic", cn: "批评家"}, {en: "criticise", cn: "评论，批评"}, {en: "criticism", cn: "批评，批判"}, {en: "critical", cn: "批评的；关键性的"}, {en: "condemn", cn: "谴责；声讨"}]},
      { group: "大约", words: [{en: "approximately", cn: "近似地，大约"}, {en: "about", cn: "大约；关于"}, {en: "around", cn: "到处；大约；周围"}]},
      { group: "征收", words: [{en: "levy", cn: "征收；征税"}, {en: "charge", cn: "费用，收费；控告"}, {en: "toll", cn: "征收"}]},
      { group: "恢复", words: [{en: "recovery", cn: "恢复，复原"}, {en: "revive", cn: "苏醒；复活；恢复"}, {en: "renaissance", cn: "文艺复兴"}, {en: "restore", cn: "修复；恢复"}]},
      { group: "屈服", words: [{en: "submit", cn: "屈服；提交"}, {en: "succumb", cn: "屈从"}, {en: "yield", cn: "屈服"}]},
      { group: "开发利用", words: [{en: "exploit", cn: "开发，开采"}, {en: "use", cn: "使用；利用"}, {en: "usage", cn: "使用，用法"}]},
      { group: "造成", words: [{en: "pose", cn: "造成，形成"}, {en: "cause", cn: "引起"}, {en: "lead to", cn: "导致"}, {en: "induce", cn: "引起"}]},
      { group: "广泛的", words: [{en: "widespread", cn: "普遍的，广泛的"}, {en: "throughout", cn: "自始至终；遍及；方方面面"}, {en: "anywhere", cn: "无论何处；任何地方"}]},
      { group: "反应", words: [{en: "response", cn: "响应；反应；回复"}, {en: "respond", cn: "回答；作出反应"}, {en: "reaction", cn: "反应"}, {en: "react", cn: "反应"}]},
      { group: "格式", words: [{en: "format", cn: "版式；格式"}, {en: "structure", cn: "结构，建筑物"}]},
      { group: "保持", words: [{en: "detain", cn: "留住"}, {en: "hold", cn: "持有；约束，控制"}, {en: "attain", cn: "达到；获得"}, {en: "retain", cn: "保持"}, {en: "maintain", cn: "保持；维护"}]},
      { group: "安全", words: [{en: "security", cn: "安全；证券"}, {en: "safety", cn: "安全"}]},
      { group: "残疾", words: [{en: "disabled", cn: "残疾的；有缺陷的"}, {en: "physically difficult", cn: "生理困难的"}]},
      { group: "约定", words: [{en: "commitment", cn: "承诺"}, {en: "engagement", cn: "约定；订婚"}]},
      { group: "比对", words: [{en: "contrast", cn: "对比，对照；差异"}, {en: "compare", cn: "比较"}]},
      { group: "内向的", words: [{en: "introverted", cn: "内向的，含蓄的"}, {en: "shy", cn: "害羞的；胆怯的"}]},
      { group: "监控", words: [{en: "monitor", cn: "监控"}, {en: "surveillance", cn: "监视"}]},
      { group: "执行", words: [{en: "execute", cn: "执行，实现"}, {en: "fulfill", cn: "履行；满足；实现"}, {en: "implement", cn: "执行"}]},
      { group: "取代", words: [{en: "instead of", cn: "代替，而不是..."}, {en: "rather than", cn: "宁可...也不愿；而不是"}]},
      { group: "间隔", words: [{en: "interval", cn: "间隔；间距"}, {en: "span", cn: "跨度，跨径"}]},
      { group: "踪迹轨道", words: [{en: "trace", cn: "踪迹；追溯"}, {en: "track", cn: "踪迹；轨道；追踪"}]},
      { group: "彻底的", words: [{en: "radical", cn: "根本的；彻底的；激进的"}, {en: "thorough", cn: "彻底的；周密的"}]},
      { group: "遵守", words: [{en: "comply", cn: "遵守；遵从"}, {en: "obey", cn: "服从；遵守"}]},
      { group: "范围", words: [{en: "range", cn: "范围"}, {en: "scope", cn: "范围；视野"}]},
      { group: "许可", words: [{en: "licence", cn: "许可证，执照"}, {en: "permit", cn: "许可；允许"}, {en: "permission", cn: "允许，许可"}]},
      { group: "道德", words: [{en: "ethical", cn: "道德的；伦理的"}, {en: "moral", cn: "道德的"}]},
      { group: "军事", words: [{en: "military", cn: "军事的；军队"}, {en: "army", cn: "军队"}]},
      { group: "娱乐休闲", words: [{en: "relaxed", cn: "放松的；悠闲的"}, {en: "recreation", cn: "娱乐；消遣"}, {en: "entertainment", cn: "娱乐"}, {en: "amusement", cn: "娱乐"}, {en: "pleasant", cn: "令人愉快的"}]},
      { group: "热带", words: [{en: "tropical", cn: "热带的"}, {en: "hot", cn: "热的"}, {en: "geography", cn: "地理"}, {en: "equator", cn: "赤道"}]},
      { group: "脆弱的", words: [{en: "subtle", cn: "微妙的，细微的"}, {en: "fragile", cn: "易碎的"}, {en: "delicate", cn: "微妙的；易碎的；精致的"}, {en: "vulnerable", cn: "易受伤的，脆弱的"}]},
      { group: "遮蔽", words: [{en: "shade", cn: "树荫；遮阳"}, {en: "shelter", cn: "庇护，避难所"}]},
      { group: "宗教", words: [{en: "religion", cn: "宗教信仰"}, {en: "religious", cn: "宗教的"}, {en: "sacred", cn: "神圣的；宗教的"}]},
      { group: "彩排准备", words: [{en: "rehearse", cn: "排练，彩排"}, {en: "rehearsal", cn: "彩排"}, {en: "preparation", cn: "准备"}, {en: "prepare", cn: "准备"}]},
      { group: "净化", words: [{en: "purify", cn: "净化"}, {en: "clean", cn: "清洁的，干净的"}]},
      { group: "紧急", words: [{en: "urgent", cn: "紧急的；急迫的"}, {en: "pressing", cn: "压，紧迫的；迫切的"}, {en: "imperative", cn: "必要的；紧急的"}, {en: "compelling", cn: "强烈的；有说服力的"}]},
      { group: "贫困", words: [{en: "poverty", cn: "贫困"}, {en: "poor", cn: "贫困的"}]},
      { group: "复制", words: [{en: "plagiarise", cn: "剽窃，抄袭"}, {en: "copy", cn: "复制；抄袭"}, {en: "duplicate", cn: "复制"}, {en: "replicate", cn: "复制；重复"}, {en: "mimic", cn: "模仿"}, {en: "imitate", cn: "模仿"}]},
      { group: "顶峰", words: [{en: "summit", cn: "最高点，峰顶"}, {en: "top", cn: "上方，顶部"}, {en: "peak", cn: "顶点；山峰"}]},
      { group: "味道", words: [{en: "odour", cn: "气味"}, {en: "smell", cn: "嗅觉"}, {en: "aroma", cn: "芳香，气味"}, {en: "olfaction", cn: "嗅觉"}, {en: "scent", cn: "气味，香味"}]},
      { group: "夜间", words: [{en: "nocturnal", cn: "夜间的"}, {en: "night", cn: "夜晚"}]},
      { group: "湿度", words: [{en: "moisture", cn: "湿度，潮湿"}, {en: "humidity", cn: "湿度，潮湿"}, {en: "wet", cn: "湿的，潮湿的"}, {en: "damp", cn: "潮湿"}, {en: "humid", cn: "潮湿的"}]},
      { group: "干旱", words: [{en: "drought", cn: "干旱"}, {en: "dry", cn: "干的"}]},
      { group: "不公平的", words: [{en: "lopsided", cn: "不平等的，不对称的"}, {en: "uneven", cn: "不平坦的；不平行的"}]},
      { group: "宠溺", words: [{en: "indulge", cn: "沉溺；满足"}, {en: "spoil", cn: "损坏；毁掉；溺爱"}]},
      { group: "寒冷", words: [{en: "freeze", cn: "结冰"}, {en: "cold", cn: "冷"}, {en: "chill", cn: "寒冷，寒颤"}]},
      { group: "饥饿", words: [{en: "famine", cn: "饥荒，饥饿"}, {en: "hunger", cn: "饿，饥饿"}]},
      { group: "耗尽", words: [{en: "exhausted", cn: "耗尽的；筋疲力尽的"}, {en: "fatigue", cn: "疲劳，疲乏"}]},
      { group: "罪犯", words: [{en: "crime", cn: "罪行，犯罪"}, {en: "criminal", cn: "罪犯"}, {en: "conviction", cn: "信仰；定罪"}]},
      { group: "混乱", words: [{en: "confuse", cn: "使混乱；使困惑"}, {en: "puzzle", cn: "使…困惑，迷惑"}]},
      { group: "吸引", words: [{en: "magnetic", cn: "有磁性的，有吸引力的"}, {en: "attractive", cn: "吸引的, 有吸引力的"}]},
      { group: "决心", words: [{en: "determine", cn: "下决心，决定；限定"}, {en: "decide", cn: "决定，下决心"}]},
      { group: "性别", words: [{en: "gender", cn: "性；性别"}, {en: "sex", cn: "性；性别"}]}
    ]
  },
  {
    unit: "第十单元",
    categories: [
      { group: "高频学术词汇", words: [{en: "economic", cn: "经济实惠的；经济学的"}, {en: "formula", cn: "公式，准则"}, {en: "function", cn: "功能；作用"}, {en: "occur", cn: "发生；举行；存在"}, {en: "percent", cn: "百分比；部分"}, {en: "role", cn: "作用，职责；角色"}, {en: "source", cn: "来源；原始资料"}, {en: "theory", cn: "理论；原理；学说"}, {en: "achieve", cn: "取得；实现"}, {en: "acquisition", cn: "获得；收购"}, {en: "administration", cn: "管理"}, {en: "aspect", cn: "方面"}, {en: "chapter", cn: "章节"}, {en: "commission", cn: "委托，委员会；佣金"}, {en: "computer", cn: "电脑"}, {en: "conclusion", cn: "结论"}, {en: "conduct", cn: "实施，进行"}, {en: "consequence", cn: "结果；后果"}, {en: "cultural", cn: "文化的"}, {en: "equation", cn: "等式；相等"}, {en: "injury", cn: "伤害，损害"}, {en: "investment", cn: "投资"}, {en: "item", cn: "项目"}, {en: "journal", cn: "日记，杂志"}, {en: "purchase", cn: "购买"}, {en: "resource", cn: "资源"}, {en: "constitutional", cn: "宪法的，体制的"}, {en: "democracy", cn: "民主"}, {en: "strategy", cn: "战略，策略"}, {en: "survey", cn: "调查"}, {en: "text", cn: "文本；课文"}, {en: "core", cn: "核心；要点"}, {en: "justify", cn: "证明；辩护"}, {en: "layer", cn: "层，阶层；地层"}, {en: "outcome", cn: "结果"}, {en: "partner", cn: "合伙人；伙伴"}, {en: "philosophy", cn: "哲学"}, {en: "publish", cn: "发表；出版"}, {en: "register", cn: "登记；注册"}, {en: "specify", cn: "列举；详细说明"}, {en: "task", cn: "任务"}, {en: "technical", cn: "技术的"}, {en: "technique", cn: "技巧，手法，技术"}, {en: "technology", cn: "科学技术"}, {en: "validity", cn: "有效，效用，合法性"}, {en: "insert", cn: "插入；嵌入"}, {en: "apparent", cn: "显然的；表面上的"}, {en: "attribute", cn: "归因于…"}, {en: "civil", cn: "公民的"}, {en: "code", cn: "代码；法规"}, {en: "conference", cn: "会议"}, {en: "cycle", cn: "循环；骑自行车"}, {en: "debate", cn: "辩论，争论"}, {en: "despite", cn: "不管，尽管"}, {en: "dimension", cn: "维度；程度"}, {en: "emerge", cn: "出现；显出；暴露"}, {en: "error", cn: "错误，过失"}, {en: "ethnic", cn: "种族的；人种的"}, {en: "impose", cn: "强加，利用；欺骗；征税"}, {en: "label", cn: "标签"}, {en: "output", cn: "产量；输出"}, {en: "overall", cn: "总体的；全面的"}, {en: "parallel", cn: "平行；平行线"}, {en: "parameter", cn: "参数"}, {en: "prior", cn: "在先的，在前的；优先的"}, {en: "professional", cn: "职业的，专业的"}, {en: "regime", cn: "政权，政体；制度"}, {en: "maintenance", cn: "维持；保养，维护"}, {en: "series", cn: "系列，连续"}, {en: "status", cn: "身份，地位，状况"}, {en: "subsequent", cn: "随后的，继…之后的"}, {en: "summary", cn: "概括摘要；简要的"}, {en: "clause", cn: "条款"}, {en: "consult", cn: "咨询，商议"}, {en: "contact", cn: "接触，联系"}, {en: "discretion", cn: "慎重，谨慎"}, {en: "draft", cn: "草稿；起草"}, {en: "enable", cn: "使能够"}, {en: "equivalent", cn: "相等的，相当的"}, {en: "generation", cn: "一代人，同时代的人"}, {en: "logic", cn: "逻辑"}, {en: "margin", cn: "边缘，利润"}, {en: "network", cn: "网络"}, {en: "psychology", cn: "心理学"}, {en: "pursue", cn: "从事；追赶"}, {en: "ratio", cn: "比率"}, {en: "revenue", cn: "收入，收益"}, {en: "trend", cn: "趋势，倾向"}, {en: "version", cn: "版本"}, {en: "edition", cn: "版本"}, {en: "welfare", cn: "福利；福利事业"}, {en: "abstract", cn: "抽象；摘要"}, {en: "aggregate", cn: "总计；聚集"}, {en: "author", cn: "作者"}, {en: "bond", cn: "结合，约定；债券"}, {en: "brief", cn: "简短的；摘要"}, {en: "federal", cn: "联邦的"}, {en: "fee", cn: "费用"}, {en: "flexibility", cn: "灵活性"}, {en: "furthermore", cn: "而且，此外"}, {en: "incidence", cn: "发生率"}, {en: "incorporated", cn: "股份有限公司的"}, {en: "index", cn: "指数；索引"}, {en: "input", cn: "输入"}, {en: "neutral", cn: "中立的，中性的"}, {en: "preceding", cn: "在先的，在前的"}, {en: "presumption", cn: "假定，认定"}, {en: "rational", cn: "理性的；合理的"}, {en: "subsidiary", cn: "附带的，附属的；子公司"}, {en: "subordinate", cn: "下属，下级；从属"}, {en: "tape", cn: "录音，带子"}, {en: "transformation", cn: "变化，转变"}, {en: "adult", cn: "成年人，成年的"}, {en: "advocate", cn: "提倡，主张"}, {en: "channel", cn: "引导"}, {en: "comprise", cn: "包含，组成"}, {en: "contrary", cn: "相反的，相反，对立"}, {en: "convert", cn: "转变，转化"}, {en: "decade", cn: "十年"}, {en: "empirical", cn: "实证的，实证研究的"}, {en: "equipment", cn: "设备；装备"}, {en: "file", cn: "文件，归档"}, {en: "foundation", cn: "建立，创办；基础，基金"}, {en: "hierarchy", cn: "等级制度"}, {en: "identical", cn: "同一的"}, {en: "ideology", cn: "意识形态"}, {en: "infer", cn: "推断，推知"}, {en: "innovation", cn: "创新"}, {en: "media", cn: "媒体"}, {en: "style", cn: "风格"}, {en: "paradigm", cn: "范例"}, {en: "phenomenon", cn: "现象"}, {en: "publication", cn: "发表，出版"}, {en: "reverse", cn: "反转；翻转；相反的"}, {en: "simulation", cn: "模拟，模仿"}, {en: "somewhat", cn: "稍微，有点"}, {en: "successive", cn: "连续的，相继的"}, {en: "thesis", cn: "论文"}, {en: "voluntary", cn: "自愿的，志愿的；义务的"}, {en: "accompany", cn: "陪伴，陪同"}, {en: "appendix", cn: "附录，附加物；阑尾"}, {en: "appreciation", cn: "欣赏，鉴赏；感激"}, {en: "arbitrary", cn: "随意的；专横的"}, {en: "contemporary", cn: "当代的"}, {en: "contradiction", cn: "矛盾"}, {en: "currency", cn: "货币；通货"}, {en: "denote", cn: "表示，指示"}, {en: "deviation", cn: "背离，偏离"}, {en: "exhibit", cn: "显示；展览"}, {en: "fluctuation", cn: "波动"}, {en: "highlight", cn: "强调，突出"}, {en: "infrastructure", cn: "基础设施，基建"}, {en: "inspection", cn: "检查，视察"}, {en: "nuclear", cn: "原子能的"}, {en: "paragraph", cn: "段落"}, {en: "schedule", cn: "安排；时间表"}, {en: "deadline", cn: "最后期限"}, {en: "termination", cn: "结束，终止，停止"}, {en: "via", cn: "通过；经由"}, {en: "virtual", cn: "实质上的，事实上的；虚拟的"}, {en: "accommodation", cn: "住处"}, {en: "analogous", cn: "相似的"}, {en: "behalf", cn: "代表；方面，利益"}, {en: "bulk", cn: "容量；大多数"}, {en: "coincide", cn: "一致，符合；同时发生"}, {en: "concurrent", cn: "同时存在的"}, {en: "confined", cn: "被限制的"}, {en: "controversy", cn: "争论"}, {en: "conversely", cn: "相反地"}, {en: "device", cn: "装置，设备"}, {en: "devote", cn: "奉献，专注"}, {en: "distortion", cn: "变形；扭曲"}, {en: "insight", cn: "洞察力；洞见"}, {en: "intermediate", cn: "中间的；中级的"}, {en: "manual", cn: "手工的"}, {en: "mature", cn: "成熟的"}, {en: "medium", cn: "媒介，手段，方法；中间"}, {en: "mutual", cn: "相互的,；共有的"}, {en: "overlap", cn: "重叠；重复"}, {en: "protocol", cn: "礼仪"}, {en: "qualitative", cn: "定性的，性质的"}, {en: "refine", cn: "精炼，提纯；改善"}, {en: "rigid", cn: "严格的；死板的"}, {en: "route", cn: "路途"}, {en: "scenario", cn: "情节，情形；方案"}, {en: "sphere", cn: "范围；球体"}, {en: "subordinate", cn: "下属，下级；从属"}, {en: "suspended", cn: "暂停的，缓期的"}, {en: "temporary", cn: "临时的，暂时的"}, {en: "unified", cn: "统一的，统一标准的"}, {en: "violation", cn: "违反，冒犯"}, {en: "vision", cn: "幻象；美景"}, {en: "adjacent", cn: "邻近的"}, {en: "colleague", cn: "同事"}, {en: "compile", cn: "编译"}, {en: "conceive", cn: "构思，设想"}, {en: "convince", cn: "劝服，使信服"}, {en: "encounter", cn: "遭遇"}, {en: "forthcoming", cn: "即将到来的"}, {en: "inclination", cn: "倾向，爱好，斜坡"}, {en: "likewise", cn: "也；同样地"}, {en: "ongoing", cn: "前进的；进行的"}, {en: "panel", cn: "面板"}, {en: "whereby", cn: "凭什么"}, {en: "versatile", cn: "多用途的，多功能的"}, {en: "persuade", cn: "说服，劝告"}, {en: "paralyse", cn: "麻痹"}, {en: "mercury", cn: "汞"}, {en: "keen", cn: "热衷的，渴望"}, {en: "instalment", cn: "分期付款"}, {en: "harbour", cn: "庇护，庇护所；海港"}, {en: "evolve", cn: "演变；进化"}, {en: "revolution", cn: "革命"}, {en: "encyclopaedia", cn: "百科全书"}, {en: "dazzle", cn: "使……目眩眼花"}, {en: "cater", cn: "迎合；提供服务"}, {en: "addictive", cn: "上瘾的"}, {en: "subject", cn: "学科，主题；主体"}]}
    ]
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = vocabularyData;
}
